Repository tryanzu/frontend, pull requests merged in 2019-10, with the labels that each got.

#28 feat(users): last seen indicator
  package-lock.json
  src/board/components/author.js
  src/board/components/chat.js
  src/board/components/comment.js
  src/board/components/feed.js
  src/board/components/navbar.js
  src/board/components/post.js
  src/board/components/quickstart.js
  src/themes/autumn/_common.scss
Labels: feature

#29 Feature/site config
  src/board/components/configModal.js
  src/board/fractals/auth.js
  src/themes/autumn/_common.scss
  src/themes/autumn/components/_modal.scss
Labels: feature

#34 chore(chat): componentization file split
  src/board/components/chat.js
  src/board/components/chatLogItem.js
  src/board/components/chatMessageInput.js
  src/board/components/chatMessageItem.js
  src/board/components/chatMessageList.js
  src/board/containers/chat.js
  src/board/containers/home.js
  src/board/utils.js
  src/streams.js
Labels: enhancement

#33 feat(drafts): drafts for post and comments
  src/board/components/comment.js
  src/board/components/feed.js
  src/board/components/publisher.js
  src/board/components/reply.js
  src/hooks/useStoredState.js
  src/i18n.js
Labels: feature

#36 fix(comment): hide the empty comment box message
  src/board/components/post.js
Labels: enhancement

#38 feat: webpack bundler
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/board/components/chatMessageInput.js
  src/board/containers/chat.js
  src/board/fractals/auth.js
  src/drivers/ext/glue.js
  src/drivers/tribute.js
  src/mount.js
  src/requests.js
  src/themes/autumn/_typicons.scss
  src/themes/autumn/app.css
  src/themes/autumn/autumn.scss
  src/themes/autumn/components/_chat.scss
  src/themes/autumn/font/typicons.eot
  src/themes/autumn/font/typicons.svg
  src/themes/autumn/font/typicons.ttf
  src/themes/autumn/font/typicons.woff
  src/themes/autumn/font/typicons.woff2
  src/themes/autumn/theme.scss
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: dependencies, enhancement

#39 feat(feed): custom scrollbar & increased feed default limit
  src/board/fractals/board.js
  src/drivers/tribute.js
  src/themes/autumn/_common.scss
Labels: enhancement
