Repository tryanzu/frontend, pull requests merged in 2019-11, with the labels that each got.

#40 fix(comment): editing and deleting tools, only for the author
  src/board/components/comment.js
Labels: bug

#44 Twitch video implementation
  package.json
  src/board/components/chatChannelSettingsModal.js
  src/board/containers/chat.js
Labels: enhancement, feature

#41 Feature/replace tachyons colours2
  src/board/components/feed.js
  src/board/components/forgotPassword.js
  src/board/components/login.js
  src/board/components/navbar.js
  src/board/components/post.js
  src/board/components/profile.js
  src/board/components/signup.js
  src/board/components/usersModal.js
  src/themes/autumn/_common.scss
Labels: feature
